# Generated by Django 4.1.4 on 2022-12-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('C', 'Children')], default='', max_length=5),
        ),
    ]
