# Generated by Django 4.1.4 on 2023-01-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='text_fielssdsfgdfgfd'),
            preserve_default=False,
        ),
    ]
