# Generated by Django 4.1.4 on 2023-01-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='title',
        ),
    ]
