# Generated by Django 4.1.4 on 2023-01-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderitem_ordered_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
