# Generated by Django 4.1.4 on 2023-01-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://cdn.igp.com/f_auto,q_auto,t_pnopt9prodlp/banners/flowers_igp_frames_20230102.jpg', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
