# Generated by Django 4.1.4 on 2023-01-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(height_field='150', unique=True, upload_to='media/uploads/', width_field='200'),
        ),
    ]
