# Generated by Django 4.1.4 on 2023-01-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(unique=True, upload_to='media/uploads/'),
        ),
    ]
