# Generated by Django 4.1.4 on 2023-01-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='500X500.png', upload_to='media/uploads/'),
        ),
    ]
