# Generated by Django 4.1.4 on 2023-01-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='long_description',
            field=models.TextField(default='Long_description', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
