# Generated by Django 4.1.4 on 2023-01-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_item_long_description_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_info',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
