# Generated by Django 4.1.4 on 2023-01-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_item_reviews_remove_reviews_user_reviews_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
