# Generated by Django 4.1.4 on 2023-01-17 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_alter_reviews_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='media/baskets/500X500.png', upload_to='media/baskets/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='hamper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gift Hamper', max_length=20)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.basket')),
            ],
        ),
        migrations.CreateModel(
            name='hamperProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('C', 'Chocolates'), ('I', 'Another Item')], max_length=35)),
                ('image', models.ImageField(default='media/uploads/500X500.png', upload_to='media/uploads/')),
                ('price', models.FloatField()),
                ('description', models.CharField(default='No description for this product', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='additional_info',
            field=models.TextField(blank=True, default='No additional info given by the seller', max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='hamperItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('hamper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hamper')),
                ('hamper_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hamperproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hamper',
            name='item',
            field=models.ManyToManyField(to='core.hamperproduct'),
        ),
    ]
