# Generated by Django 4.1.4 on 2023-01-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_basket_hamper_hamperproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamperitem',
            name='hamper',
        ),
        migrations.AddField(
            model_name='hamperitem',
            name='hamper',
            field=models.ManyToManyField(to='core.hamper'),
        ),
    ]
