# Generated by Django 4.1.4 on 2023-01-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_hamperitem_hamper_hamperitem_hamper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamperitem',
            name='hamper_products',
        ),
    ]
