# Generated by Django 4.1.4 on 2023-01-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_hamperitem_hamper_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamper',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
