# Generated by Django 4.1.4 on 2023-01-17 11:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_hamper_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='core_item_search__67155a_gin'),
        ),
    ]
