# Generated by Django 4.1.4 on 2023-01-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_item_search_vector_item_core_item_search__67155a_gin'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='order',
            name='hamper',
            field=models.ManyToManyField(to='core.hamperitem'),
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to='core.image'),
        ),
    ]
