# Generated by Django 4.1.4 on 2023-01-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_image_remove_item_image_order_hamper_item_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/products/')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ManyToManyField(to='core.images'),
        ),
    ]
