# Generated by Django 4.1.4 on 2023-01-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_category_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
    ]
