# Generated by Django 4.1.4 on 2023-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_order_hamper'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Not ordered', max_length=400),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Not ordered', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Not ordered', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default='Not ordered', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Not ordered', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
