# Generated by Django 4.1.4 on 2023-01-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='BillingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.billingaddress'),
        ),
    ]
