# Generated by Django 4.1.4 on 2023-01-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_order_billingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='appartment_address',
            new_name='apartment_address',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='street_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
